apiVersion: v1
kind: Service
metadata:
  name: fodmap-service
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: fodmap-service
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}