app:
  name: ${rootProject.name}
  description: ${description}
  encoding: ${compileJava.options.getEncoding()}
  version: ${version}
  java:
    target: ${targetCompatibility}
    source: ${sourceCompatibility}

management:
  endpoints:
    web:
      base-path: "/private"
      exposure:
        include: "prometheus,readiness"
      path-mapping:
        prometheus: "metrics"

downstreams:
  - name: HeightApp
    address: http://localhost:9000/heightapp
  - name: SleepApp
    address: http://localhost:9000/sleepapp

spring:
  data:
    cassandra:
      port: 9042
#      Change this to cassandra-service when deploying to local k8s cluster
      contact-points: 127.0.0.1
      keyspace-name: fodmap
  security:
    user:
      name: username
      password: password